const types = {
  DUMMY_ACTION: 'DUMMY_ACTION',
  FETCH_ALL_TODOS: 'FETCH_ALL_TODOS',
  FAIL_ALL_TODOS: 'FAIL_ALL_TODOS',
  SUCCESS_ALL_TODOS: 'SUCCESS_ALL_TODOS',
  FILTER_BY: 'FILTER_BY',
  ADD_TODO: 'ADD_TODO',
  DELETE_TODO: ' DELETE_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
};

export default types;
