const types = {
  DUMMY_ACTION: 'DUMMY_ACTION',
  FETCH_ALL_TODOS: 'FETCH_ALL_TODOS',
  FAIL_ALL_TODOS: 'FAIL_ALL_TODOS',
  SUCCESS_ALL_TODOS: 'SUCCESS_ALL_TODOS',
  FILTER_BY: 'FILTER_BY',
  ADD_TODO: 'ADD_TODO',
  SUCCESS_ADD_TODO: 'SUCCESS_ADD_TODO',
  FAIL_ADD_TODO: 'FAIL_ADD_TODO',
  DELETE_TODO: ' DELETE_TODO',
  SUCCESS_DELETE_TODO: ' SUCCESS_DELETE_TODO',
  FAIL_DELETE_TODO: ' FAIL_DELETE_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
  SUCCESS_TOGGLE_TODO: 'SUCCESS_TOGGLE_TODO',
  FAIL_TOGGLE_TODO: 'FAIL_TOGGLE_TODO',
};

export default types;
